import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillBook, AiFillGithub } from "react-icons/ai";
import Avatar from "../../public/Avatar.png";
// import SoftwareEngineer from '../../public/'
import ScreenShot from "../../public/Screenshot 2023-04-24 181902.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nick Wells Portfolio</title>
        <meta name="description" content="Generated by create next.js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1>Developed By Nick Wells</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="curso-pointer text-xl" />
              </li>
              <li>
                <a
                  href="https://www.linkedin.com/in/nick-wells-04b13a26a/overlay/1635529050977/single-media-viewer/?profileId=ACoAAEHfIrsBLnHh3uNU8YC0j93isazFkroM_gQ"
                  target="_blank"
                  className="bg-gradient-to-r from-purple-500 ml-10 px-4 py-2 rounded-md"
                />
                Resume
              </li>
            </ul>
          </nav>
          <div className="text-center p-12">
            <h2 className="text-5xl py-2 font-medium text-purple-600">
              Nick Wells
            </h2>
            <h3 className="text-xl py-2"> Software Engineer and Developer</h3>
            <p className="text-md py-5 leading-8">
              Software Engineer from Flatiron School, With a specialty in
              JS/React and Ruby!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-14 py-3 text-gray-400">
            <a
              href="https://www.linkedin.com/in/nick-wells-04b13a26a"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://medium.com/@wellsnick3" target="_blank">
              <AiFillBook />
            </a>
            <a href="https://github.com/Risingsheild" target="_blank">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradent-to-b from-purple-500 rounded-xl w-80 h-80 mt-15 py-8 overflow-hidden">
            <Image src={Avatar} alt="Personal photo" />
          </div>
        </section>
        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1 bg-gradient-to-r from-purple-500">
              Projects Portfolio
            </h3>
            <p className="text-md py-5 leading-8">
              Since the beginning of my journey as a Software Engineer I have
              worked on various projects..
            </p>
          </div>
          <br />
          <div className="text-center flex justify-center">
            <a href="https://youtu.be/Xi6-AG69Vsk" target="_blank">
              <h3 className="text-xl py-6 px-5 mr-10 bg-gradient-to-r from-teal-300">
                Pharmacy Scheduling Application
                <p className="text-sm italic">click for video </p>
              </h3>
            </a>
            <p className="text-md py-4 leading-8">
              This is a full Stack Appilcation, The Frontend uses React
              framework with a Redux State management system, while I use Ruby
              and PSQL as the Backend and Database.
            </p>
          </div>
          <div className="flex justify-center gap-14 py-3">
            <Image
              src={ScreenShot}
              alt="Pharmacy Application"
              height={300}
            />
          </div>
        </section>
      </main>
    </div>
  );
}
