import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillBook, AiFillGithub } from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nick Wells Portfolio</title>
        <meta name="description" content="Generated by create next.js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1>Developed By Nick Wells</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="curso-pointer text-xl" />
              </li>
              <li>
                <a
                  href="S:\Software Engineer Resume.pdf"
                  className="bg-gradient-to-r from-purple-500 ml-8 px-4 py-2 rounded-md"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-12">
            <h2 className="text-5xl py-2 font-medium text-purple-600">
              Nick Wells
            </h2>
            <h3 className="text-xl py-2"> Software Engineer and Developer</h3>
            <p className="text-md py-5 leading-8">
              Software Engineer from Flatiron School, With a specialty in
              JS/React and Ruby!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-14 py-3 text-gray-400">
            <a
              href="https://www.linkedin.com/in/nick-wells-04b13a26a"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://medium.com/@wellsnick3" target="_blank">
              <AiFillBook />
            </a>
            <a href="https://github.com/Risingsheild" target="_blank">
              <AiFillGithub />
            </a>
          </div>
          <div className="">{/* <Image src={}/> */}</div>
        </section>
      </main>
    </div>
  );
}
